# Site settings
site: mairacanal
title: Maíra Canal
keywords: software, blog, open-source
description: >-
 Kernel development and embedded systems 
lang: en-US
timezone:  Brazil/São Paulo

# Author settings
author:
  name: Maíra Canal
  bio: computer engineering @ USP <br> systems dev, embedded systems, operational systems, compilers <br> open source enthusiast /#linux
  picture: assets/images/profile.jpg 
  github: mairacanal # github username
  linkedin: mairacanal # linkedin username
  email: maira.canal@usp.br # email adress


# URL settings
url: "http://mairacanal.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
