name: Build and publish site
on:
 push:
   branches: ["main"]
jobs:
  page:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: action/checkout@v3
      # Setup ruby
      - uses: ruby/setup-ruby@v1
      # Install dependencies
      - run: bundle install
      # Build with jekyll
      - run: bundle exec jekyll build
      # Publish
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
